### ISSUE TITLE
would you be able to license this code via apache-like open source license ?

### ISSUE THREAD

**Issue by datalackey** [dancerjohn/LibEx#1]
Hi, John - 
I tried your library and it worked great. I would like to include this functionality in to-be-open-sourced code i am writing for a client...and would really like to use it in future projects as well, because i often need  to verify the output that i am logging.

unfortunately when i did a maven repo search i could not find the compiled binary in maven central and similar repos.  

Would you consider making the code available via something like the apache license ?
[ https://github.com/blog/1530-choosing-an-open-source-license ]

many thanks in advance
 -chris

**Comment by dancerjohn** [comment]
Sure. I will do so this weekend.

**Comment by datalackey** [comment]
if you are ever in mountain view / palo alto (ca)  area,  we will buy you a beer !    thanks ;^)

**Comment by dancerjohn** [comment]
Done. Sorry for the delay
